### ISSUE TITLE
Le premier mois de colle n’apparaît pas dans le ramassage

### ISSUE THREAD

**Issue by blotg** [stephanekirsch/e-colle#10]
Bonjour,

Dans l'onglet "ramassage" de la partie du site réservée au secrétariat, le seul mois ramassable est le mois d'octobre, alors que des colles ont eu lieu en septembre. De plus, le nom des mois est indiqué en anglais dans les menus déroulants (alors qu'ils sont en français ailleurs sur le site).

S'il s'agit d'une erreur de configuration de ma part, je m'en excuse.

**Comment by stephanekirsch** [comment]
C'est étrange, le premier mois est calculé en cherchant le mois du permier jour de la première (par ordre chronologique) semaine de colle. Si jamais une exception est levée, il prend le mois courant. C'est probablement ce qui se passe, mais je ne vois pas ce qui pourrait causer cela. Quel est votre première semaine de colle?
(Tout cela est géré dans le fichier accueil/models.py dans la fonction mois() lignes 832-843)

**Comment by blotg** [comment]
Merci de votre réponse !
Effectivement, c'est bien dans la fonction date que l'erreur se produit.
Elle vient plus précisément de la ligne 832 : 
`moisMax=date(moisMax.year+moisMax.month//12,moisMax.month+1,1)-timedelta(days=1)
`
L'erreur disparaît lorsque je supprimer le "+1", il doit donc s'agir du 2e argument qui excède 12 dans mon cas.
Pour info, les semaines de colles s'étendent de la semaine du 10/09/18 à la semaine du 03/12/18.
Je continue de chercher d'où vient l'erreur dès que j'ai du temps libre.

**Comment by stephanekirsch** [comment]
Bonjour,
Merci pour le retour,
L’erreur vient effectivement du calcul de moisMax.
Il faut remplacer moisMax + 1 par mousMax % 12 + 1. Je fais ça dans la journée.
Encore merci !

**Comment by stephanekirsch** [comment]
Voilà c'est fait. Ça devrait marcher correctement maintenant (Ce bug était passé inaperçu car c'est rare que le dernier moins de colle soit décembre!)

**Comment by blotg** [comment]
Oui, c'est vrais, j'imagine.
Merci beaucoup pour tout !!!
