### ISSUE TITLE
Bug ajout colle dans colloscope

### ISSUE THREAD

**Issue by sebreyt** [stephanekirsch/e-colle#15]
Bonjour,

Lorsque j'essaye de modifier le colloscope, la liste de tous les colleurs est décalée de façon assez étrange, avec des mélanges entre matière. Ce qui a l'air de poser le problème est le fait qu'un colleur ait plusieurs matières à son actif, et que toutes ces matières ne soient pas enseignées dans la classe dont on modifie le colloscope. J'espère être clair...

Ce que j'ai pu remarquer : le colleur ayant deux matières apparaît deux fois, une fois au bon endroit, et la deuxième fois en première position de la matière suivante de la liste. Si il y a deux colleurs dans ce cas là dans la même matière, le deuxième apparaît aussi deux fois.

Si je peux donner plus d'infos n'hésite pas. Tu peux encore regarder le comportement du colloscope à partir de mon compte dont je n'ai pas changé le mot de passe (ici le problème se pose pour les profs de français, pour lesquels j'ai dû créer deux matières, une avec des colles de 20 min et l'autre avec des colles de 30 min).  

Merci !

**Comment by stephanekirsch** [comment]
Bonjour,
normalement le problème est résolu dans le dernier commit (sur les 3 branches master/RGPD/2019). Ton analyse était exacte: chaque colleur apparaissait autant de fois qu'il avait de matières, même celles que la classe n'avait pas. Ça décalait tout, dans d'autres matières (et les colleurs de la fins finissaient à la poubelle en plus).
J'en ai profité pour empêcher d'enlever une matière d'une classe si il y avait des notes ou des colles dans cette matière (sinon erreur 500 en allant sur la page du collloscope).
Merci beaucoup!
