### ISSUE TITLE
Update ImageMagick

### ISSUE THREAD

**Issue by sebreyt** [stephanekirsch/e-colle#18]
Bonjour, 

Depuis que j'ai mis à jour mon serveur, et notamment ImageMagick, les images jpg correspondant au programme de colles pdf ne sont plus générées. Le problème vient d'un problème de droit inhérent à ImageMagick. Je ne pense pas que ecolle puisse faire grand chose contre ça, mais si d'autres tombent sur le problème, je l'ai résolu en modifiant `/etc/ImageMagick-6/policy.xml` et en modifiant la ligne   `<policy domain="coder" rights="none" pattern="PDF" />` et en remplaçant `none` par `read|write` (
https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453).

Bonne journée !

Seb

**Comment by stephanekirsch** [comment]
merci pour ces précisons! À l'occasion j'essaierai de l'intégrer dans la doc.
