### ISSUE TITLE
wishlist: messages élèves -> colleurs

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#20]
Permettre (option à choisir selon la politique des établissements) aux élèves de joindre leurs colleurs serait utile pour trouver des solutions déplacer les colles, notamment lorsque les colleurs n'enseignent pas dans l'établissement.

**Comment by stephanekirsch** [comment]
Salut Didier!
oui c'est pas faux, ça doit pouvoir s'implémenter pas trop difficilement en rajoutant une option booléenne dans la config. Je vais voir ça (mais ça va me forcer à changer les appli mobiles aussi ... :()

**Comment by stephanekirsch** [comment]
bon voilà j'ai ajouté une option dans la config pour autoriser les élèves à écrire des messages autrement qu'en répondant,
