### ISSUE TITLE
Installation sur server Always Data

### ISSUE THREAD

**Issue by Tonio51170** [stephanekirsch/e-colle#21]
Bonjour, 

Je tente une installation sur un server Always Data depuis plusieurs jours et si j'arrive bien à faire toutes les étapes d'installation, je n'arrive pas à accéder au site une fois celui-ci installé.

En cherchant dans les logs, j'obtiens un énigmatique : 

ModuleNotFoundError : No Module named 'ecolle'

au moment de l'execution de get_wsgi_application() à l'intérieur de wsgi.py (qui lui est bien trouvé donc la définition du chemin de l'application n'est pas en cause)

Je poste ce message au cas où quelqu'un aurait déjà eu ce problème, j'avoue sécher complètement ...

**Comment by stephanekirsch** [comment]
il s'agissait d'un probleme de virtualenv mal configuré.
