### ISSUE TITLE
App mobile : amélioration possible ?

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#22]
Bonjour,
Concernant l'application mobile, serait-il possible quand on crée une note de mettre par défaut la "bonne" semaine, le jour, et l'horaire la plus proche ?

J'ai eu plusieurs fois des soucis de déconnexion de l'appli lors de la rentrée des notes. Quand je fais envoyer, il me dit "Etes vous sur de vouloir vous déconnecter" alors que je n'ai rien demander. Le soucis est qu'il efface alors les notes que je venais de rentrer pour le groupe.
Serait-il possible à minima de ne pas effacer les données en cas de déconnexion ? Eventuellement de demander si on veut recharger les anciennes données non transmises ?

**Comment by stephanekirsch** [comment]
Bonjour Alain,
pour la première demande ça doit pouvoir se faire relativement facilement. J'en profite pour rappeler que si vous avez défini un colloscope vous pouvez directement noter depuis l'agenda: pour les colles révolues, un petit crayon apparait et envoi sur la page de notation en préremplissant semaine/heure/groupe ou élève, il ne reste qu'à mettre la note et l'éventuel commentaire pour chaque élève.
Concernant ton bug, le message est exactement celui-là ou bien ça parle de session expirée?
Peux-tu me donner ta version d'android? En attendant tu peux essayer de sauvegarder en brouillon les notes au lieu de les envoyer directement (icone disquette), puis les envoyer depuis la page des notes où tu verras les brouillons de note apparaître (tu auras un icone envoyer qui apparait en haut à droite).
Je vais essayer d'enquêter pour voir comment un clic sur envoyer peut te faire déconnecter...

**Comment by alaincaignot** [comment]
Je vais essayer de rentrer mon colloscope pour tester, mais pour le moment nous sommes partis en les rentrant à la volée dans toutes les classes.

Concernant mon bug, je ne me souviens plus exactement, mais il me semble que c'est "Etes vous sur de vouloir vous déconnecter. Les brouillons  ne seront pas sauvegardés" ou quelque chose dans le genre. Je colle vendredi maintenant, je noterais ou ferais une capture. 
Sinon d'accord, je passerais peut être par l'enregistrement, de mémoire, il faut envoyer les notes une par une ensuite.
Mon matériel Samsung S6, android 7.0, je suis en 4G quand je le fais.

**Comment by stephanekirsch** [comment]
Tu peux envoyer les brouillons tous en même temps si tu cliques sur l'icone d'envoi tout en haut (pas sur ceux qui sont sur les brouillons).

**Comment by stephanekirsch** [comment]
Alors pour ce qui est de mettre la bonne semaine/jour/heure ce sera mis à la prochaine mise à jour des applis mobiles.
Pour tes problèmes de déconnexion, c'est dû au fait qu'après un long temps à l'arrière plan, l'"activité" est détruite. Au moment où tu reviens sur l'appli, elle est recréée, et c'est là que j'avais mal géré et que la gestion des cookies (dont le cookie de session) n'était plus faite. Normalement c'est aussi réglé à la prochaine mise à jour (d'ici une semaine j'espère).

**Comment by stephanekirsch** [comment]
voilà c'est réglé dans la dernière maj iOS/android
