### ISSUE TITLE
App mobile : noter depuis l'agenda

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#23]
Bonjour,
Est-il possible d'ajouter la notation depuis l'agenda comme sur le site ?
Merci
Alain Caignot

**Comment by stephanekirsch** [comment]
Bonjour Alain,
c'est déjà implémenté. Si tu remontes dans la liste de ton agenda, tu vois les colles révolues avec un petit crayon pour aller les noter.

**Comment by alaincaignot** [comment]
Bonjour
Je ne vois pas de petit crayon, regarde ma capture d'écran.
Quand je clique sur une colle ca me dit "pas de programme".
Alain

Le mar. 1 oct. 2019 à 13:26, stéphane Kirsch <notifications@github.com> a
écrit :

**Comment by stephanekirsch** [comment]
c'est étrange, si aucune note n'est emregistrée sur ce créneau, un crayon doit apparaître (si la case est un peu grisée pour signifier que cette colle est déjà passée).

**Comment by alaincaignot** [comment]
Effectivement là j'ai mis des notes sur ses créneaux manuellement depuis
notes.

Donc je viens de faire deux tests :
- en créant une colle la semaine de la rentrée : pas de soucis
- en créant une colle mardi à 16h. Il est 16h20 et le créneau n'est pas
grisé... Je pense que c'est pour ca que j'ai pas vu le crayon...

Je suis en train de me dire que la notion de révolue est que tu n'as pas
prévu de noter avant la fin effective de la colle ? Donc à 17h ca sera bon
j'imagine... Peut être même pas, je viens de la décaler à 15h et elle n'est
toujours pas grisée...
Par contre si je la modifie en mettant la date d'hier cette fois, c'est
grisé et j'ai le crayon.

Il y a peut être une petit quelque chose quand même sur le passage en grisé
? Pour moi ca serait bien que ce soit modifiable dès le début de la colle
afin de pouvoir mettre les annotations directement.






Le mar. 1 oct. 2019 à 14:50, stéphane Kirsch <notifications@github.com> a
écrit :

**Comment by stephanekirsch** [comment]
probablement un problème de fuseau horaire (différence entre heure GMT et heure locale), je vais corriger ça.

**Comment by stephanekirsch** [comment]
voilà c'est corrigé dans la dernière maj iOS/android

**Comment by alaincaignot** [comment]
Après 1 petit mois d'utilisation, tout est résolu.
Eventuellement, quand on ouvre l'appli, l'agenda nous met la "1ère colle suivante", tu pourrais décaler d'un cran pour voir la colle à noter qui est juste au dessus.
