### ISSUE TITLE
Gestion des droits de modification du colloscope

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#24]
Bonjour,
En tant que prof principal quand on ajoute les droits de modification du colloscope à un collègue, quand on se déconnecte puis reconnecte la case n'est plus cochée...

Serait-il possible d'ajouter dans l'interface colleur (de l'administrateur) ; ou dans le profil colleur, une résumé des droits ? 

Merci d'avance
Alain Caignot

**Comment by stephanekirsch** [comment]
C'est bizarre... C'est enregistré en base de donnée dans le profil de prof. Il n'y a pas de raison qu'il perde les droits. Je vais regarder ça.

**Comment by alaincaignot** [comment]
Les droits sont gardés mais le prof principal ne voit plus qu'ils ont été
donnés : la case qu'il a cochée, n est plus cochée.



Le mar. 1 oct. 2019 à 13:29, stéphane Kirsch <notifications@github.com> a
écrit :

**Comment by stephanekirsch** [comment]
ok je vais regarder ça

**Comment by stephanekirsch** [comment]
effectivement, il y avait un petit oubli dans le formulaire. C'est corrigé!
