### ISSUE TITLE
Des messages inaccessibles?

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#25]
J'ai posée une question à tous les khôlleurs via les "messages" d'e-colle.
Je pense que certains m'ont répondu, mais je n'arrive pas à accéder à leurs réponses: ma liste de messages ne fait pas apparaître les 5 messages non-lus que je m'attend à y trouver:
![image](https://user-images.githubusercontent.com/11584405/66723657-11528500-edf2-11e9-91be-9b878a161b03.png)

Les messages non lus sont probablement des réponses au premier de la liste, le message du 8 octobre.

**Comment by stephanekirsch** [comment]
Salut Didier,
ton problème est étrange! Je viens de faire plusieurs tests sur le serveur de test et je n'obtiens rien de tel :(
les lignes 95 à 101 de ton fichier forms.py ressemblent à ca?:

class SelectMessageForm(forms.Form):
    def __init__(self,user,*args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)
        query=Message.objects.filter(Q(auteur=user,hasAuteur=True)|Q(messagerecu__user=user)).distinct().order_by('-date')
        self.fields['message'] = CustomMultipleChoiceField(queryset=query, required=True,widget = forms.CheckboxSelectMultiple)
        self.fields['message'].empty_label=None

**Comment by didierherisson** [comment]
Bonjour,
C'est bien cela, autant que je puisse en juger.
J'ai également eu des messages qui sont bien passés avec leurs réponses, je ne saurais pas comment produire un MWE...
Est-ce que je peux vérifier qqch pour toi dans la BDD, pour comprendre pourquoi ces messages sont comptés comme non-lu mais pas affichés?

**Comment by stephanekirsch** [comment]
Ben difficile de dire quoi vérifier si je sais pas quoi chercher. Si tu peux m’envoyer un dump des tables accueil_message et accueil_destinataire je pourrais comprendre je pense

**Comment by stephanekirsch** [comment]
merci pour les données que tu m'as envoyées, ça m'a permis de cerner le problème que j'ai corrigé.
Si tu veux le corriger à la main plutôt que de faire une maj complète, il faut replacer la ligne 148 du fichier accueil/views.py par:
`Destinataire(user=message.auteur,message=mesage).save()`
en fait il faut juste enlever un 's' au dernier mot 'message' de la ligne.
Je te renvoie par mail ton dump en faisant correctement les liens pour que tu puisse lire tes réponses :)
