### ISSUE TITLE
Ordre alphabétique

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#27]
Bonjour,
Nous avons remarqué avec les collègues un "problème" d'ordre alphabétique entre notre application de notes classiques (ou Excel) et Ecolle.
Cela concerne la gestion des espaces des noms à particules.

Je pense que le tri est fait en supprimant les espaces. Par exemple, l'appli classera les élèves suivant comme ca : 
De Benjamin
Decours 
De rien
Dumoulin
Du toit

Et excel ou notre appli notes : 
De Benjamin
De rien
Decours
Du toit
Dumoulin

Voilà si tu peux faire quelque chose en cette période de report de notes :)
Alain

**Comment by stephanekirsch** [comment]
Bonjour alain,
Le tri dépend de l'interclassement de ta base de données, c'est indépendant de e-colle.
Cela dit, j'ai changé l'édition du fichier csv en séparant les nom/prénoms des élèves pour pouvoir facilement retrier la liste des élèves.

Stéphane

**Comment by alaincaignot** [comment]
Bonjour,
Alors quand je regarde la base de donnée e-colle (postgre) est en collation
fr_FR.UTF8.
Dans la table accueil_user, le champ last_name est en collation
pg_catalog."default".

J'ai modifier la collation de last_name en pg_catalog."C-UTF-8" et ca
semble fonctionner... J'espère que ca ne posera pas de soucis ailleurs.
Peut être aurais-je du modifier la collation de la base de données... Je ne
sais pas à quoi fait référence la collation default dans postgresql. J'ai
cru lire des choses contradictoires entre les paramètres systèmes et les
paramètres de la base...

Alain


Le sam. 9 nov. 2019 à 10:39, stéphane Kirsch <notifications@github.com> a
écrit :
