### ISSUE TITLE
Appli Androïd: pb d'accès au serveur.

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#28]
Depuis ce WE si j'en crois mes élèves, l'appli e-colle ne se connecte plus au serveur. Je l'ai vérifié sur Androïd, mais je crois que c'est pour tous.
Ma mise à jour de l'appli est datée du 13 novembre.

**Comment by stephanekirsch** [comment]
ha zut. Tu pourrais m'envoyer par mail un login/mdp d’élève pour que je teste?

**Comment by stephanekirsch** [comment]
j'ai refait une mise à jour il y a quelques jours. Je ne peux pas tester sur un téléphone android là, est-ce que ça remarche?
