### ISSUE TITLE
wishlist : décompte des colles / affichage des relevés effectués

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#29]
Bonjour,
Serait-il possible d'ajouter dans la partie "décompte", une mise en forme permettant de dire le nombre d'heures qui ont été relevées par le secrétariat avec la date ? 
Ca permettrait de faire le lien entre la fiche de paie et le relevé plus facilement. 
Merci
Alain

**Comment by stephanekirsch** [comment]
Bonjour Alain,
ca ne devrait pas être bien compliqué. Je rajoute sur ma Todo liste de la rentrée 2020!

**Comment by stephanekirsch** [comment]
Bonjour,
j'ai rajouté le nombre d'heures ramassées en parallèle du nombre d'heures effectuées, ainsi que des liens pour avoir les pdfs des différents ramassage (pour soi uniquement bien sûr)
