### ISSUE TITLE
Wishlist: enseignement partagé/tuilage entre enseignants: plusieurs enseignants pour une matière.

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#31]
Bonjour,

La possibilité d'ajouter plusieurs enseignants pour une classe sur une matière peut parfois être utile.

Dans le cas qui m'intéresse, il s'agit d'un enseignant qui part en cours d'année et est donc remplacé sur la fin de l'année.  Le départ est anticipé, le remplaçant identifié quelques semaines avant,  le titulaire et lui peuvent se coordonner. Afin de permettre le meilleur tuilage entre les enseignants, il serait souhaitable que les deux aient accès à la vue "enseignant" pendant un certain temps.

-> lorsqu'un enseignant est attribué à une matière dans une classe, un bouton permettrait d'en ajouter un second, avec les mêmes droits.

**Comment by stephanekirsch** [comment]
Je vais réfléchir à la façon dont on pourrait l'implémenter!

**Comment by stephanekirsch** [comment]
C'est fait, on peut maintenant mettre autant de profs qu'on veut pour une même matière (au lycée Fabert la LV1 angais est partagée entre plusieurs profs, donc je peux imaginer que c'est comme ça dans beaucoup d'établissements)
