### ISSUE TITLE
bug : problème recherche colleur par matière ET par classe

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#35]
Bonjour,
La recherche par matière fonctionne, par classe aussi mais si je couple les deux le résultat est incorrect.
Merci d'avance

**Comment by stephanekirsch** [comment]
effectivement, je vais enquêter sur le problème...

**Comment by stephanekirsch** [comment]
Après enquête il apparaît évident que lorsqu'on précise les deux (classe + matière), lors de la requête SQL, django intervertit l'ordre des paramètres: il met l'id de la matière au lieu de celui de la classe et inversement... du coup le résultat obtenu est effectivement absurde. Ce que je ne comprends pas c'est pourquoi cela arrive... a priori mon code est bon (de toute façon je ne peux filter les classes que sur une valeur de classe et idem pour les matières, sinon mon code planterait).
Je vais voir quand j'aurai un peu plus de temps comment contourner ce problème. Le soucis c'est qu'il faut obligatoirement un queryset, pas possible de contourner le problème avec une requête brute..

**Comment by stephanekirsch** [comment]
bon le problème ne venait pas de Django! C'est moi qui intervertissait à un endroit du code les 2! C'est réglé!
