### ISSUE TITLE
L'import de colleurs en csv ne fonctionne pas

### ISSUE THREAD

**Issue by erachen** [stephanekirsch/e-colle#36]
Bonjour Stéphane,

Lorsqu'on import des colleur en csv,
/administrateur/action/colleur/csv

la première étape se passe bien (le .csv est lu et le formulaire reflète bien son contenu)
mais a la validation du 2ème formulaire, la page affiche une erreur en:
- réaffichant  le premier formulaire
- en en disant qu'il manque des champs obligatoires.

J'ai l'impression que la validation du 1er formulaire devrait plutot renvoyer vers la page
/administrateur/action/colleur/ajouter

Cordialement.

-- 
Vincent

**Comment by stephanekirsch** [comment]
Bonsoir,
l'erreur m'avait effectivement été remontée, et elle est corrigée!
Merci :)

**Comment by erachen** [comment]
Merci, je vais déployer le correctif :-)
