### ISSUE TITLE
Sécurisation du site avec SSL

### ISSUE THREAD

**Issue by Tonio51170** [stephanekirsch/e-colle#4]
Bonjour, 

Pour la sécurisation en SSL il existe aussi Letsencrypt qui, mis en place avec dehydrated, permet une certification gratuite du site sans avoir ces pages de confirmations dans les navigateurs.

Un très bon manuel : https://technique.arscenic.org/ssl-securisation-des-communications-serveur-client/article/installer-et-configurer-un-certificat-let-s-encrypt

Merci pour votre travail !

A. Mériaux (Maths au lycée Roosevelt de Reims en MPSI)

**Comment by stephanekirsch** [comment]
Bonjour Antoine,
C’est tout-à-fait exact, c’est d’ailleurs ce que j’utilise depuis un peu plus d’un an. Je n’ai par contre pas encore eu/pris le temps de le mettre dans la documentation :(
