### ISSUE TITLE
deploiement et contribution

### ISSUE THREAD

**Issue by erachen** [stephanekirsch/e-colle#40]
Bonjour Stéphane,

Je déploie beaucoup ce type de projet en utilisant git, et comme `config.py` et `debug.py` sont dans l'arbre git,
 ça coince et ça m'oblige à les mettre de côté avec un `git stash`, puis un `git stash pop` et j'aime pas trop faire ça en production.

D'autre part, lorsque je teste ce projet sur ma machine, je perd fréquemment ma config en changeant de branche (`config.py` se trouve écrasé).
Dans mes pratiques de développement cela se résout en sortant de l'arbre git les fichiers variables dont font partie
`config.py` et `debug.py`.

J'ai préparé une PR dans ce sens (#37), peux tu y jeter un œil et/ou proposer une autre manière de faire ?
Ça simplifierait ma vie de d'admin/sys et de contributeur occasionnel :)

Cordialement.

**Comment by stephanekirsch** [comment]
Merci, je vais regarder ça en détail très vite. Il faut que je vérifie et/ou que je modifie des trucs pour que ça fonctionne bien aussi avec le fichier update.py

**Comment by stephanekirsch** [comment]
avec beaucoup de retard c'est rajouté. Merci encore, c'est vrai que ça change la vie de ne plus avoir à effacer les mots de passe avant de commit :)

**Comment by erachen** [comment]
glad to help :)
