### ISSUE TITLE
erreur 500 sur /app_mobile/messages

### ISSUE THREAD

**Issue by erachen** [stephanekirsch/e-colle#41]
Je reçois des TB par mail:

a priori c'est dans:

`app_mobile/views.py:197` dans  messages()

https://github.com/stephanekirsch/e-colle/blob/734836c6deaff79fb0fe8a27c12b1ae3558f48f2/app_mobile/views.py#L197

`classe` n'est pas défini.
Je ne suis pas sur de la logique de cette fonction, ni ou aller chercher `classe` dans ce cas là (`user.eleve.classe` ou `user.colleur.classes`), ou s'il faut simplement ne pas filtrer sur `classe`.

**Comment by stephanekirsch** [comment]
merci beaucoup pour ce retour, c'est corrigé :)

**Comment by erachen** [comment]
j'ai poussé le correctif en prod. merci :)
