### ISSUE TITLE
admin est hardcodé avec 'admin@example.com'

### ISSUE THREAD

**Issue by erachen** [stephanekirsch/e-colle#42]
dans
https://github.com/stephanekirsch/e-colle/blob/734836c6deaff79fb0fe8a27c12b1ae3558f48f2/ecolle/settings.py#L20

le mail de l'admin (celui qui reçoit les rapport d'erreur) est hardcodé et est défini après l'import de `config.py`, bref les erreur partent vers `admin@exemple.com` et finissent par revenir sous forme de bounce au postmaster.

Est il possible d'utiliser `EMAIL_ADMIN` à la place ?

**Comment by stephanekirsch** [comment]
merci, c'est mergé :)
