### ISSUE TITLE
Bug : passage d'une sélection en lv2

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#44]
Bonjour
Quand je passe une sélection dans une LV2, ça me écrase la LV1... Et ne fais rien sur la LV2.

Merci d avance
Alain

**Comment by stephanekirsch** [comment]
Bonjour Alain,
je ferme puisque cela a été corrigé il y a 3 semaines.
Cordialement,
Stéphane Kirsch
