### ISSUE TITLE
Erreur 500 - Problème serveur

### ISSUE THREAD

**Issue by mathsmpwallon** [stephanekirsch/e-colle#45]
Bonjour, lorsque l'on veut consulter les résultats d'une classe (la MP), on obtient le message suivant : Erreur 500 - Problème serveur

C'est la seule classe qui rencontre ce problème et c'est la première fois que cela arrive. Savez-vous ce qui peut causer cet incident ? 

Merci.

**Comment by stephanekirsch** [comment]
bonsoir,
sans plus de détails difficile de répondre. Le plus simple est de passer la variable debug a True pour avoir un message d'erreur détaillé, auquel cas je pourrai plus vous aider.
Il me semble qu'au lycée Henri Wallon vous êtes à la version 2.0, qui n'est plus très à jour :( C'est possiblement un bug qui a été corrigé avec le passage à une version plus récente.

**Comment by jowe19** [comment]
Bonjour, 
Au passage, je rencontre cette erreur en tant qu'admin, sur la version 2.3, dans l'onglet Semaines. Voici ce que j'obtiens comme message.

```
Environment:


Request Method: GET
Request URL: https://ecolle.prepabarthou.fr/administrateur/action/semaine

Django Version: 3.1.1
Python Version: 3.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'accueil.apps.accueilConfig',
 'administrateur.apps.administrateurConfig',
 'eleve.apps.eleveConfig',
 'colleur.apps.colleurConfig',
 'secretariat.apps.secretariatConfig',
 'app_mobile.apps.appMobileConfig',
 'customfilter.apps.customfilterConfig',
 'ckeditor')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/html/e-colle/administrateur/views.py", line 48, in wrapped_view
    return func(request, *args, **kwargs)
  File "/var/www/html/e-colle/administrateur/views.py", line 267, in semaine
    return render(request,'administrateur/semaine.html',{'semaines':semaines,'form':form, 'form2': form2 })

Exception Type: UnboundLocalError at /administrateur/action/semaine
Exception Value: local variable 'semaines' referenced before assignment
```

**Comment by mathsmpwallon** [comment]
Bonjour à tous,

je ne peux pas vous confirmer que mon problème initiale a disparu car je ne peux pas me connecter. D’habitude, je sélectionne mon nom dans un menu déroulant. Ce menu n’existe plus.

Merci en tous cas de votre investissement pendant cette pause estivale.

Cordialement,


--
M. Bonnet
Maths MP
Laboratoire Claire Voisin
https://cahier-de-prepa.fr/mp-wallon
Lycée H. Wallon, Valenciennes

**Comment by stephanekirsch** [comment]
Bonjour,
concernant le menu déroulant, il a disparu à la version 2.1. Ce n'est pas du tout RGPD compatible que n'importe qui ait accès à la liste des colleurs et des élèves de l'établissement. Depuis la 2.1 la connexion se fait par identifiant / mot de passe.
C'est l'utilisateur "administrateur" qui a accès à ces informations. Il faudrait probablement qu'il sélectionne d'un coup tous les colleurs pour les modifier et leur générer un identifiant (ça peut se faire pour tous les colleurs en même temps en mettant comme identifiant prenom.nom).
Je jette un oeil sur le soucis du bug des semaines.

**Comment by stephanekirsch** [comment]
je viens de résoudre le problème des semaines. En espérant que le reste fonctionne bien!

**Comment by jowe19** [comment]
> je viens de résoudre le problème des semaines. En espérant que le reste fonctionne bien!

Je confirme, c'est résolu. Merci !
