### ISSUE TITLE
Ramassage heures négatives : notes supprimées par un colleur après un ramassage

### ISSUE THREAD

**Issue by sebreyt** [stephanekirsch/e-colle#47]
Bonjour, 

Notre secrétaire a essayé de faire un ramassage pour décembre et est tombée sur une erreur serveur. Après en avoir été informé, je suis allé voir sur un profil colleur -> erreur serveur en essayant d'aller voir les résultats (je ne sais pas laquelle, j'avais debug sur False). 
Après un reboot du serveur je n'ai plus de problème visible côté colleur, mais il y a toujours un problème du côté du ramassage : aucun problème pour les autres ramassages d'octobre ou de novembre, et pas de problème non plus si "tout ramasser depuis le début" est coché. 

Voici l'erreur en question.
(1690, "BIGINT UNSIGNED value is out of range in '(`e-colle`.`dec2`.`temps` - coalesce(`e-colle`.`dec1`.`temps`,0))'")
Si besoin de plus de détail je peux coller toutes les infos de debug. 
Je précise que je n'ai pas touché au serveur depuis quelques temps et que tout tournait nickel (je n'ai pas fait l'update sur les derniers commits mais ils n'ont pas l'air lié à ce problème)

Merci et bonne année !

**Comment by sebreyt** [comment]
Bonjour Stéphane,
Merci pour le commit. Je ne sais pas s'il était censé régler le problème à lui seul, mais ça ne fonctionne malheureusement toujours pas. Quelques infos de debug si jamais ça aide (pas sûr que ce soient les passages les plus parlants ?) :


/var/www/html/e-colle/secretariat/views.py, line 317, in ramassagePdf

        listeDecompte, effectifs = Ramassage.objects.decompteRamassage(ramassage, csv = False, parClasse = False, parMois=parMois, full = full)

Variable | Value
-- | --
LISTE_MOIS | ['',  'Janvier',  'Février',  'Mars',  'Avril',  'Mai',  'Juin',  'Juillet',  'Août',  'Septembre',  'Octobre',  'Novembre',  'Décembre']
LISTE_MOIS_COURT | ['jan',  'fev',  'mar',  'avr',  'mai',  'juin',  'juil',  'aou',  'sep',  'oct',  'nov',  'dec']
debut | datetime.date(2020, 12, 1)
fin | datetime.date(2020, 12, 31)
full | 0
id_ramassage | '65'
moisdebut | 24251
parMois | 0
ramassage | <Ramassage: Ramassage object (65)>
request | <WSGIRequest: GET '/secretariat/action/ramassage/pdf/65/0/0'>
response | <HttpResponse status_code=200, "application/pdf">

 /var/www/html/e-colle/accueil/models/ramassage.py, line 124, in decompteRamassage

                cursor.execute(requete,(ramassage_precedent_pk,ramassage.pk,ramassage.pk,ramassage_precedent_pk) if not colleur else  (ramassage_precedent_pk,ramassage.pk,colleur.pk,ramassage.pk,ramassage_precedent_pk,colleur.pk))

Variable | Value
-- | --
colleur | False
csv | False
cursor | <django.db.backends.utils.CursorDebugWrapper object at 0x7facaea179d0>
full | 0
mois | datetime.date(2020, 11, 30)
parClasse | False
parMois | 0
ramassage | <Ramassage: Ramassage object (65)>
ramassage_precedent | <Ramassage: Ramassage object (44)>
ramassage_precedent_pk | 44
requete | ('SELECT  req.classe_id, req.classe_nom, req.annee, req.matiere_nom, req.etab, '  'req.grade, req.nom, req.prenom, req.colleur_id,             SUM(req.heures) '  'heures FROM (SELECT cl.id classe_id, cl.nom classe_nom, cl.annee, ma.nom '  "matiere_nom, COALESCE(et.nom, 'Inconnu') etab, col.grade, u.last_name nom, "  'u.first_name prenom, col.id colleur_id,        dec2.mois mois, '  'SUM(dec2.temps) - COALESCE(SUM(dec1.temps),0) heures        FROM '  'accueil_decompte dec2        LEFT OUTER JOIN accueil_decompte dec1        ON '  'dec1.colleur_id = dec2.colleur_id AND dec1.classe_id = dec2.classe_id AND '  'dec1.matiere_id = dec2.matiere_id        AND dec1.mois = dec2.mois AND '  'dec1.ramassage_id = %s        INNER JOIN accueil_colleur col        ON '  'dec2.colleur_id = col.id        INNER JOIN accueil_classe cl        ON '  'dec2.classe_id = cl.id        INNER JOIN accueil_matiere ma        ON '  'dec2.matiere_id = ma.id        INNER JOIN accueil_user u        ON '  'u.colleur_id = col.id        LEFT OUTER JOIN accueil_etablissement et        '  'ON col.etablissement_id = et.id        WHERE dec2.ramassage_id=%s AND '  'dec2.temps - COALESCE(dec1.temps,0) != 0        GROUP BY ma.nom, '  'u.last_name, u.first_name, col.id, cl.id, et.nom, dec2.mois        UNION ALL '  'SELECT cl.id classe_id, cl.nom classe_nom, cl.annee, ma.nom matiere_nom, '  "COALESCE(et.nom, 'Inconnu') etab, col.grade, u.last_name nom, u.first_name "  'prenom, col.id colleur_id,        dec1.mois mois, - '  'COALESCE(SUM(dec1.temps),0) heures        FROM accueil_decompte dec1        '  'LEFT OUTER JOIN accueil_decompte dec2        ON dec1.colleur_id = '  'dec2.colleur_id AND dec1.classe_id = dec2.classe_id AND dec1.matiere_id = '  'dec2.matiere_id        AND dec1.mois = dec2.mois AND '  'dec2.ramassage_id=%s        INNER JOIN accueil_colleur col        ON '  'dec1.colleur_id = col.id        INNER JOIN accueil_classe cl        ON '  'dec1.classe_id = cl.id        INNER JOIN accueil_matiere ma        ON '  'dec1.matiere_id = ma.id        INNER JOIN accueil_user u        ON '  'u.colleur_id = col.id        LEFT OUTER JOIN accueil_etablissement et        '  'ON col.etablissement_id = et.id        WHERE dec2.id IS NULL AND '  'dec1.ramassage_id = %s        GROUP BY ma.nom, u.last_name, u.first_name, '  'col.id, cl.id, et.nom, dec1.mois) as req            GROUP BY req.classe_id, '  'req.classe_nom, req.annee, req.matiere_nom, req.etab, req.grade, req.nom, '  'req.prenom, req.colleur_id            ORDER BY req.matiere_nom, req.etab, '  'req.grade, req.nom, req.prenom')
self | <accueil.models.ramassage.RamassageManager object at 0x7facaf204880>

**Comment by sebreyt** [comment]
Bonjour Stéphane, 

J'ai fini par me plonger un peu dans le monde des types SQL, et en modifiant cette ligne de ramassage.py ça fonctionne. 

        WHERE dec2.ramassage_id = %s AND CAST(CAST(dec2.temps AS SIGNED) - CAST(COALESCE(dec1.temps,0) AS SIGNED) AS SIGNED) != 0{}\

Je ne sais pas comment faire un pull request, donc je te laisse voir si c'est à peu près ce qu'il fallait faire (j'ai peut-être un peu trop multiplié les CAST...) et faire le commit. 

Merci !

**Comment by stephanekirsch** [comment]
Bonjour,
C'est étrange car c'est une volonté délibérée qu'il y ait des heures négatives au cas justement où des heures sont par exemples mal notées et donc effacées puis recréées.
Je n'ai pas rencontré le problème jusqu'à maintenant avec PostgreSQL, même avec des heures effectivement négatives.
le plus simple est probablement de changer le type du champs "temps" dans la table décompte. Elle est effectivement spécifiée positive, donc je viens de changer ça sur les branches 2.2 et master.
Attention, il faut bien lancer la commande migrate après la mise à jour.
Désolé de n'avoir pas vu ton "issue" plus tôt!
