### ISSUE TITLE
Suggestion – Message d'information sur la page d'accueil ?

### ISSUE THREAD

**Issue by jowe19** [stephanekirsch/e-colle#49]
Bonjour, 
Serait-il possible de laisser la possibilité au secrétariat et/ou admin de publier des messages d'information sur la page d'accueil d'e-colle ? 

Actuellement je le fais à la main (ici : https://ecolle.prepabarthou.fr/) en modifiant le code html mais laisser cette possibilité au secrétariat via un formulaire dans l'interface de gestion nous ferait gagner du temps 😊

**Comment by stephanekirsch** [comment]
Bonjour,
ça doit être possible pou peu d'efforts, dès que j'ai un peu de temps (pas sûr que ce soit avant la rentrée prochaine par contre).
Tu veux juste un message sur la page d'accueil et/ou la possibilité d'afficher une message d'accueil après connexion pour les colleurs / élèves?

**Comment by jowe19** [comment]
Le must ce serait d'avoir les possibilités suivantes : 1 message sur la page d'accueil visible tout le temps (connecté ou pas), 1 message post connexion qui pourrait être variable suivant le profil (élève ou colleur) car typiquement les informations de ramassage ne sont pas utiles pour les élèves.

**Comment by stephanekirsch** [comment]
C’est tout-à-fait faisable!
Reste à trouver un peu de temps pour faire ça!
