### ISSUE TITLE
Erreur server lors de l'export du colloscope en PDF

### ISSUE THREAD

**Issue by Tonio51170** [stephanekirsch/e-colle#5]
Bonjour, 

Il y a une erreur lors de l'export du colloscope en PDF s'il manque des prénoms aux collleurs. Ce n'est pas grave mais j'ai mis un moment avant de trouver que cela provenait des prénoms.

Antoine.

**Comment by stephanekirsch** [comment]
Merci beaucoup de m’en informer !
J’ai très certainement oublié de traiter le cas où le prénom vaut None... je fais ça aussi vite que possible !
Stéphane

**Comment by stephanekirsch** [comment]
Voilà normalement c’est corrigé mais je n’ai pas encore testé.
