### ISSUE TITLE
Problème pour remplir le colloscope

### ISSUE THREAD

**Issue by Tonio51170** [stephanekirsch/e-colle#50]
Bonjour, 

En MPSI, il y a le choix d'option à la fin du premier semestre et j'ai du modifier pas mal de groupes pour le second semestre.
Je n'ai qu'un groupe de germaniste (Le groupe 1) et tous les autres sont anglicistes. Après avoir changé les groupes, lorsque j'essaye de remplir les colles d'Anglais pour le second semestre, je n'ai que le G1 de proposé. Avez-vous déjà rencontré le problème ?
Une info qui peut avoir son importance, je ne sais pas, lorsque j'ai rempli les colles de maths et de physique, je ne pouvais pas choisir le G1 ...
J'ai vérifié, l'ensemble des étudiants ont bien la bonne langue de selectionné.

Si vous avez une idée ...

A. Mériaux.

**Comment by stephanekirsch** [comment]
Bonjour Antoine,
Il y avait effectivement un bug qui a été corrigé il y a environ 5 mois (donc après la rentrée) sur les groupes lors de la modification du colloscope (il a été corrigé depuis).
Est-ce que ce bug concerne l'ajout de colles « une par une » et / ou l'ajout de colle par paquet avec « créneaux multiples »?

**Comment by Tonio51170** [comment]
Il concerne l'ajout des colles "une par une". Est-ce que je peut mettre à jour mon site sans risque pour les autres classes ?

**Comment by stephanekirsch** [comment]
A priori oui. Faut juste bien penser à faire un python3 manage.py migrate après pour mettre à jour la base de données.
Cela dit si tu as peur que ça pose problème, tu peux toujours remplir tes colles avec « créneaux multiples », même en les mettant une par une.
