### ISSUE TITLE
Suggestion – Visualisation par le secrétariat des créneaux enregistrés

### ISSUE THREAD

**Issue by jowe19** [stephanekirsch/e-colle#51]
Tout est dans le titre :) Notre secrétariat souhaiterait pouvoir accéder en cas de besoin aux créneaux enregistrés par les colleurs. Merci par avance.

**Comment by jowe19** [comment]
En fait chez moi la plupart des collègues n'enregistrent pas leurs colles via le colloscope, mais les saisissent directement. Il me semble que dans ce cas le secrétariat ne peut avoir accès précisément aux heures déclarées, seulement au total ?

**Comment by stephanekirsch** [comment]
Ha oui effectivement. Je mets dans ma todo list pour la rentrée prochaine alors! Donner la possibilité au secrétariat de visualiser les notes de colle par colleur.

**Comment by jowe19** [comment]
Dans le prolongement de mon message précédent, je me disais que ce serait super si on (les enseignants) pouvait consulter le nombre d'heures déclarées par tous nos colleurs sur l'année. Cela permettrait de vérifier facilement si on dépasse l'enveloppe ou pas.

**Comment by didierherisson** [comment]
Je plussoie, utile en fin d'année pour avoir une idée des interrogateurs en retard dans leur saisie, histoire que le relevé final soit complet.

**Comment by stephanekirsch** [comment]
Ça doit être possible, sans trop de difficultés. Je rajoute à la liste :)

**Comment by stephanekirsch** [comment]
C'est fait !
