### ISSUE TITLE
Mise à jour depuis la version 2.0

### ISSUE THREAD

**Issue by CyrilAud** [stephanekirsch/e-colle#52]
Bonjour,

En charge de l'administration d'e-Colle pour le Lycée Henri Wallon, j'ai quelques soucis pour mettre à jour la version 2.0 d'e-colle.
Voici la démarche que j'ai employée :

1. En suivant le manuel, j'ai copié le contenu du répertoire accueil/management/commands de la version 2.2 dans mon e-colle et j'ai lancé le processus de mise à jour (python3 manage.py update 2.1, puis python3 manage.py update 2.2 pour tester). Résultat :
`ImportError: cannot import name 'BACKUP_ROOT' from 'ecolle.settings' (/e-colle/ecolle/settings.py)`

2. En suivant la syntaxe des fichiers de la version 2.2, j'ai donc ajouté la directive dans le fichier settings.py qui valorisait cette variable et j'ai relancé le processus de mise à jour avec ce résultat :
`cannot import name 'HEURE_DEBUT' from 'ecolle.settings' (/e-colle/ecolle/settings.py)`

3. J'ai étudié les fichiers de configuration du répertoire ecolle, par rapport aux fichiers de la branche master. J'ai donc ajouté le fichier config.py (qui n'existait pas dans la version 2.0) en le valorisant et ainsi les fichiers settings.py et debug.py de la version 2.2). J'ai relancé le processus de mise à jour, avec comme résultat :
`name 'exception' is not defined`

4. Comme dernière tentative, j'ai remplacé tous les fichiers du répertoire e-colle par ceux de la version 2.2 (en gardant le fichier ecolle/config.py adapté à mon installation) et relancé le processus de mise à jour, avec ce résultat :
`ModuleNotFoundError: No module named 'qrcode'`

Je commence à sécher. Avez-vous une solution pour mettre à jour e-colle vers la version 2.2 ? J'ai remis les fichiers de la version 2.0 (j'avais fait une copie du répertoire), je me retrouve comme après mon étape 3.

Merci d'avance.

**Comment by stephanekirsch** [comment]
Bonjour,
il y a effectivement eu pas mal de changement depuis la 2.0.
la dernière méthode utilisée est probablement la plus efficace.
Le message d'erreur sur qrcode n'est pas très grave, il suffit d'installer la bibliothèque python qrcode avec pip:
pip3 install qrcode
si vous avez d'autres soucis n'hésitez pas à me contacter directement par mail à stephane (point) kirsch (at) gmail (point) com.
Il risque d'y avoit une version 2.3 d'ici la rentrée prochaine, avec des améliorations notables, parmi lesquelles une amélioration du système de mise à jour.
Cordialement,
Stéphane Kirsch

**Comment by CyrilAud** [comment]
Bonjour,
Merci pour la réponse rapide ! La mise à jour est passée, j'attends un retour de mes collègues de CPGE afin de savoir si tout fonctionne correctement (je n'ai pas de compte permettant de me connecter à e-colle !).
Cordialement,
Cyril

**Comment by stephanekirsch** [comment]
Il faut certainement lancer un 

python3 manage.py migrate 

Pour mettre à jour la structure de la base de données. Sinon il risque d'y avoir des bugs.

Cordialement,

Stéphane skirsch

**Comment by CyrilAud** [comment]
OK, merci pour l'info !
Avant le upgrade ? Car je viens de le faire (après le upgrade), et j'ai cette erreur :
`django.db.utils.OperationalError: (1050, "Table 'accueil_decompte' already exists")`

**Comment by CyrilAud** [comment]
Après avoir remise la base de données en version 2.0, j'ai retesté la mise à jour en faisant le migrate avant. Pour le migrate, j'ai eu cette erreur :
`django.db.utils.OperationalError: (1050, "Table 'accueil_decompte' already exists")`
Et pour l'update, j'ai eu cette erreur au moment de la sauvegarde (que j'avais eu ce matin également) :
`(1146, "Table 'ecolle2.accueil_devoir' doesn't exist")`

**Comment by stephanekirsch** [comment]
oui les devoirs sont arrivés après la 2.0, donc la table n'existe pas avant le migrate, alors que la commande backup va essayer de sauver cette table.

**Comment by CyrilAud** [comment]
OK, merci de la précision !

**Comment by CyrilAud** [comment]
Bonjour, je me permets de vous relancer car je vous ai envoyé sur votre boite électronique, comme vous me l'aviez demandé, un courriel concernant la suite de mes soucis pour la mise à jour d'e-colle. L'avez vous reçu ?
Bonne journée,
Cyril
