### ISSUE TITLE
Suggestion – Envoi de mails à tous les colleurs

### ISSUE THREAD

**Issue by jowe19** [stephanekirsch/e-colle#53]
Je me demandais s'il était possible d'ajouter un moyen (bouton `mailto:...` par exemple sur la page de gestion des colleurs) afin de pouvoir facilement envoyer un mail à tous les colleurs enregistrés. Ce bouton pourrait être accessible aussi pour le secrétariat afin de pouvoir transmettre des informations. 

À défaut, pouvoir télécharger la liste des colleurs au format `.csv` serait déjà top.

**Comment by stephanekirsch** [comment]
C'est déjà possible de télécharger la liste des colleurs au format csv si on va sur "modifier"

**Comment by stephanekirsch** [comment]
et je viens de rajouter un lien dans la page colleurs (et aussi élèves du coup) pour envoyer un mail à tous les colleurs ou élèves sélectionnés.
