### ISSUE TITLE
Agenda élève: erreur serveur.

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#56]
Bonjour,

L'agenda fonctionne bien pour les enseignants, mais provoque une erreur pour les profils élèves
e-colle 2.3, serveur MySQL

Le rapport avec setdebugtrue:
<div id="summary">
  <h1>OperationalError
       at /eleve/action/agenda</h1>
  <pre class="exception_value">(1066, "Not unique table/alias: 'e'")</pre>
  

Request Method: | GET
-- | --
https://diademe.alwaysdata.net/eleve/action/agenda
3.2.6
OperationalError
(1066, "Not unique table/alias: 'e'")
/home/diademe/env_python/kholles/lib/python3.9/site-packages/MySQLdb/connections.py, line 259, in query
/usr/alwaysdata/uwsgi/2.0.18/bin/uwsgi
3.9.6
['.',  '',  '/usr/alwaysdata/python/3.9.6/lib/python39.zip',  '/usr/alwaysdata/python/3.9.6/lib/python3.9',  '/usr/alwaysdata/python/3.9.6/lib/python3.9/lib-dynload',  '/home/diademe/env_python/kholles/lib/python3.9/site-packages']
Fri, 03 Sep 2021 21:18:50 -1000

**Comment by stephanekirsch** [comment]
oui désolé c'était une grossière coquille (une ligne qui a fini en doublon dans la requete SQL...)
