### ISSUE TITLE
Compatibilité du colloscope: message "erreur du serveur" au lieu des incompatibilités.

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#57]
Bonjour,
En vérifiant les incompatibilité, je n'ai pas le listing attendu des problèmes de superpositions de colles, mais juste un message abscon "erreur du serveur" dans la pop-up qui apparait.
Lorsqu'il n'y a pas d'erreur, le message dans cette même fenêtre est celui attendu comme quoi il n'y a pas d'incompatibilité détectée.

Puisque ça a été un point clef dans un précédent dysfonctionnement, je rappelle que ma BdD est MariaDB.

**Comment by stephanekirsch** [comment]
bug a priori résolu dernièrement
