### ISSUE TITLE
Programme de colle (fichier vide)

### ISSUE THREAD

**Issue by jowe19** [stephanekirsch/e-colle#60]
Bonsoir, 
J'arrive maintenant à uploader des programmes de colle, mais la fenêtre censée afficher le fichier pdf vide.

Merci

<img width="578" alt="Capture d’écran 2021-09-17 à 00 01 40" src="https://user-images.githubusercontent.com/19306526/133691616-aa91490d-94f2-446b-bfbc-481a470e7abb.png">

**Comment by stephanekirsch** [comment]
si tu essaies de le modifier, le fichier apparaît?

**Comment by jowe19** [comment]
Voici ce que j'ai quand je clique sur "modifier". 

<img width="562" alt="Capture d’écran 2021-09-17 à 00 08 35" src="https://user-images.githubusercontent.com/19306526/133692132-d03776f2-4b99-409d-ae6c-078b247f4201.png">

**Comment by stephanekirsch** [comment]
Donc le fichier est bien présent... Est-ce que ça ne serait pas l'image de l'icône pdf qu'il ne trouve pas (et que le lien est caché quelque part dans la page?
Ça donne quoi si tu fait examiner l'élément sur la case où le pdf devrait apparaître?

**Comment by jowe19** [comment]
L'inspection de l'élément donne ceci
<img width="683" alt="Capture d’écran 2021-09-17 à 00 18 31" src="https://user-images.githubusercontent.com/19306526/133693119-fa2c8c5f-15d4-4489-918f-62d08776fcb7.png">
.

**Comment by stephanekirsch** [comment]
tu peux dérouler le td qui apparaît en rouge?

**Comment by jowe19** [comment]
Ou
<img width="673" alt="Capture d’écran 2021-09-17 à 00 23 52" src="https://user-images.githubusercontent.com/19306526/133693427-c399d3b6-83aa-499c-8411-c322b727026d.png">
i

**Comment by stephanekirsch** [comment]
donc le lien est bien présent, le problème c'est qu'il en doit pas voir l'image à l'intérieur. Si tu déroule de <a> tu va voir une balise <img>. Je suppose que lien vers l'image est mort c'est bien ça?

**Comment by jowe19** [comment]
Voilà ce que j'ai quand je déroule le dernier niveau. 

<img width="676" alt="Capture d’écran 2021-09-17 à 00 33 46" src="https://user-images.githubusercontent.com/19306526/133694184-30f79e59-a8db-47fa-a89e-1061e655cff1.png">

Et effectivement ce lien est mort.

**Comment by jowe19** [comment]
J'ai les droits suivants actuellement. 

<img width="447" alt="Capture d’écran 2021-09-17 à 00 37 20" src="https://user-images.githubusercontent.com/19306526/133694451-fe9dc207-a39d-47b5-9630-5e879b0cd7ba.png">

**Comment by stephanekirsch** [comment]
ha c'est peut-être un problème avec imageMagick alors. D'après le nom de l'image tu as choisi l'option de faire un jpg de la première page du programme. Donc ce que j'ai dit avant est faux.

**Comment by stephanekirsch** [comment]
pas de problme de droit donc. JE crains que le fichier jpg n'existe pas, tu peux vérifier?

**Comment by jowe19** [comment]
Il doit être dans le dossier image normale ?

**Comment by stephanekirsch** [comment]
oui

**Comment by jowe19** [comment]
Le dossier est vide

**Comment by stephanekirsch** [comment]
Donc c'est ImageMagick qui a un problème..

**Comment by jowe19** [comment]
Merci pour ton aide. Alors du coup j'ai fait un :
`sudo chmod -R 770 media ecolle/config.py`

depuis le répertoire e-colle mais cela ne semble pas encore résoudre le problème.

**Comment by stephanekirsch** [comment]
Ça vient peut-être de ImageMagick alors. depuis quelques années il faut faire une manip pour autoriser la conversion des pdf avec ImageMagick. Je ne sais pas si tu l'as faite. Elle est faite dans le fichier e-colle/imagemagick.py
Essaie donc de lancer depuis le répertoire e-colle
sudo python3 imagemagick.py
et regarde si la conversion fonctionne après ça.

**Comment by jowe19** [comment]
<img width="849" alt="Capture d’écran 2021-09-17 à 11 06 42" src="https://user-images.githubusercontent.com/19306526/133756506-0f97487d-ad2c-41c0-a9e8-aaad8ea72285.png">

Alors ça semble résolu à présent, modulo le petit bug d'affichage de la vignette :) (sur Safari du moins)

**Comment by stephanekirsch** [comment]
Ha ça c'est parce que j'ai calculé la position de l'image en supposant que c'était un format A4 portrait :(
