### ISSUE TITLE
[bug] souci dans la vérification du colloscope

### ISSUE THREAD

**Issue by didierherisson** [stephanekirsch/e-colle#68]
Quand y a pas de souci, le bouton de vérification fonctionne correctement semble-t-il: une popup apparaît et confirme "aucune incompatibilité détectée".
Mais quand il y a une incompatibilité détectée, j'ai un message "erreur serveur". Et là, j'ai une 'erreur serveur' après le remplissage des créneaux de français, j'aimerai bien le détail...
Le message 'erreur serveur' arrive dans une popup et pas en gros en rouge. J'ai essayé de passer en mode debug=true, rien de plus.

Version 2.3, MaJ en réinitialisant mon année il y a 3 semaines.

**Comment by didierherisson** [comment]
MaJ sur master pour le bug du DS, ce n'est pas lié à la date de ma dernière MaJ semble-t-il.

**Comment by stephanekirsch** [comment]
problème résolu
