### ISSUE TITLE
Cas particulier / Élèves provenant de trinômes différents

### ISSUE THREAD

**Issue by sebreyt** [stephanekirsch/e-colle#69]
Bonjour Stéphane, 
On a cette année été obligés, pour de sombres histoires de colles de langue, de mélanger différents trinômes sur certains créneaux. Mais je bute au moment de les rentrer dans le colloscope : j'aimerais pouvoir déclarer des créneaux sous la forme 1ab+7b, mais cette syntaxe n'a l'air de fonctionner que pour les colles solo si j'ai bien compris, en tout cas je n'ai pas réussi. Est-il possible d'étendre ce comportement aux colles déclarées par trinôme ? Sans que ce soit trop prise de tête bien entendu...
Au passage, en séparant dans le csv deux groupes par un ";" j'ai pu déclarer ces deux groupes sur un même créneau mais je ne sais pas quel va être l'effet quand le colleur va cliquer sur "noter", et je me demande si c'est un bug ou une "feature" de pouvoir déclarer deux groupes ainsi.
Merci et bonne rentrée ! 
Sébastien

**Comment by stephanekirsch** [comment]
Bonjour Sébastien,
A vrai dire ça dépend de la version de e-colle que tu utilises. Sur la 2.4 le fait de planifier par groupe/ élève n'est plus lié à la matière donc pour n'importe quelle matière, tu peux planifier par groupe ou élève.
Pour ce qui est de mettre 2 groupes sur un même créneau, c'est justement prévu pour les langues. Par exemple en LV1 anglais tu peux mettre 2 groupes sur un créneau (voire même 3) pourvu que le nombre total d'élèves qui font LV1 anglais ne dépasse pas 3. Si tu fais ça, le colleur ne verra et ne pourra noter que les élèves anglicistes. Du côté élève, seuls les anglicistes des groupes de colle mis sur ce créneau d'anglais verront la colle dans leur agenda.

**Comment by sebreyt** [comment]
Merci pour ta réponse. Je suis bien passé à la 2.4, j'imagine que le problème est que j'avais choisi de ne pas utiliser les lv1/2 parce que ça me compliquait certains trucs. et ça ne m'avait pas posé problème jusque là. 
En revanche, si je te comprends bien, je devrais pouvoir déclarer 1ab+7b dans le colloscope lors de l'import, mais j'ai une erreur serveur (not enough values to unpack (expected 2, got 1)) dès que je mets par exemple 1ab. Est-ce normal ?  
Merci encore !

**Comment by stephanekirsch** [comment]
Ha ben ça c'est probablement un bug que j'ai laissé passer. Je jetterai un oeil ce soir si j'ai le temps.

**Comment by sebreyt** [comment]
Quand t'auras le temps évidemment, rien ne presse. 
Et ça sent le bug parce que si je mets seulement "1a" (alors que j'ai simplement des trinômes sur les autres semaines), j'ai toutes les semaines en groupe "classe" pour le créneau en question. Si ça peut t'aider à trouver vite !

**Comment by stephanekirsch** [comment]
Normalement c'est corrigé! (moyennant une petite update bien sûr sur master ou 2.4)

**Comment by sebreyt** [comment]
Ça marche à la perfection, comme d'hab ! Merci encore
