### ISSUE TITLE
Affichage du programme de colle

### ISSUE THREAD

**Issue by Domlol** [stephanekirsch/e-colle#70]
Quand j'ajoute un programme de colle en ne cochant qu'une semaine, tout va bien, mais si je coche deux cases de semaines, il apparaît ensuite deux fois dans la liste en dessous (et 4 fois si j'en coche 4, exemple sur la capture ci-jointe).
J'utilise la dernière version de e-colle.
Merci
![Capture d’écran 2022-10-09 103647](https://user-images.githubusercontent.com/10160309/194746680-9fdcb996-4d26-45e0-9270-c925d902c53d.png)

**Comment by stephanekirsch** [comment]
Bonjour,
merci pour cette remontée de bug.
Effectivement il y a manifestement un soucis.
Je viens de le corriger et de mettre à jour les version 2.4 et master.
Dès que votre admin aura fait la mise à jour du serveur le bug disparaîtra.
En vous souhaitant un bon dimanche!
Stéphane Kirsch
