### ISSUE TITLE
Wishlist : génération des mots de passe et vérification des nouveaux mdp

### ISSUE THREAD

**Issue by alaincaignot** [stephanekirsch/e-colle#73]
Bonjour,

Suite à un entretien avec la DSI de mon établissement, serait-il possible d'ajouter un paramètre pour fixer la longueur des mots de passe générer automatiquement dans le fichier config.py ? L'objectif serait de passer la longueur à 10 voir 12 (ou plus ?)...
Serait-il possible d'ajouter des contraintes minimales : 2 minuscules, 2 majuscules, 2 chiffres, 2 ponctuations + complétement à taille minimale ?

De même serait-il possible de vérifier si le mot de passe changé dans le profil par les utilisateurs vérifies les dites spécifications ?

Je mets modestement 2 bouts de fonctions qui permettent de répondre à la question en pièce jointe.
Merci d'avance
Alain
[fct_password.zip](https://github.com/stephanekirsch/e-colle/files/11303045/fct_password.zip)

**Comment by stephanekirsch** [comment]
J'ai intégré les changements aux dernière versions, en rajoutant des fonctions de vérification de mots de passe (à configurer directement dans le fichier config.py).
