### ISSUE TITLE
Message d'erreur " Config() got unexpected keyword arguments: 'modif_ects' "

### ISSUE THREAD

**Issue by AhmedSouai** [stephanekirsch/e-colle#75]
Bonjour,

Lors de l'exécution en local du site web e-colle j'ai ce message d'erreur 

![error](https://github.com/stephanekirsch/e-colle/assets/59059201/99b796b5-d664-4269-9a4c-58e28c51729e)

Si quelqu'un aurait une explication ? Thanks

**Comment by stephanekirsch** [comment]
Bonjour,

La base de données n'est probablement pas à jour. Il faut lancer la commande 
python3 manage.py migrate

Cordialement,

Stéphane Kirsch

**Comment by AhmedSouai** [comment]
Bonjour,

Tout d'abord merci de m'avoir répondu : j'ai effacer ma bdd puis je l'ai réimporter de  0 avec la commande " python3 manage.py migrate" mais j'ai toujours la même erreur.

Je suis sous une Debian 12
la version du linux 6.1.0-9-amd64.

Merci.

**Comment by AhmedSouai** [comment]
Bonjour,

J'ai trouvé l'erreur vous vous   êtes tromper dans le code 
![erreur modif_ects](https://github.com/stephanekirsch/e-colle/assets/59059201/33020e06-9765-4e6e-a224-c156da4ef4b6)
![erreur modif_ects2](https://github.com/stephanekirsch/e-colle/assets/59059201/4b121fa1-c94a-47ff-ab53-ad65a574c2dd)
Vous avez ecrit modif_ects au lieu de ects_modif

Cordialement.

**Comment by stephanekirsch** [comment]
Merci,

Je vais corriger ça!
Cordialement,

Stéphane Kirsch

**Comment by AhmedSouai** [comment]
Bonjour,

J'ai également trouver une deuxieme erreur dans le fichier install.py
Dans la fonction main() ne fonctionne pas lorsque on a des version de python supérieur a 3.9  par exemple on a une version 3.11.2  on ne peut pas comparer les versions sous forme de chaine de caracteres on ne peut pas non plus les comparer sous forme de décimaux car nous avons deux points dans notre version
![correction python](https://github.com/stephanekirsch/e-colle/assets/59059201/266b363b-77a4-4dbf-8b46-84aba33e542c)

Donc voici le code  qui résolut le problème

Cordialement.

**Comment by stephanekirsch** [comment]
C'est résolu, merci pour cette remontée
