### ISSUE TITLE
Lien incorrect vers le manuel secrétariat dans le wiki

### ISSUE THREAD

**Issue by blotg** [stephanekirsch/e-colle#9]
Dans le wiki, le lien pour le manuel secrétariat pointe vers
https://github.com/stephanekirsch/e-colle/blob/master/doc/manuel_eleve.pdf
au lieu de
https://github.com/stephanekirsch/e-colle/blob/master/doc/manuel_secretariat.pdf
Sinon, bravo et merci pour ce formidable travail !

**Comment by stephanekirsch** [comment]
Merci, c'est corrigé :)
